### ISSUE TITLE
Chrome Extension building

### ISSUE THREAD

**Issue by Clem-** [istupakov/manga-downloader#1]
Hi there,
If Manga Downloader is a real Chrome extension, why do we have to build it?
I am on a Chromebook and I can't build the extension to use it with Chrome browser.
Thank you.

**Comment by istupakov** [comment]
Hi! You can try to use builded extension file - manga-downloader-v1.3.crx from [release](https://github.com/istupakov/manga-downloader/releases/latest).

**Comment by Clem-** [comment]
Awesome, thank you!
